### ISSUE TITLE
Create home page for buzz 2k15

### ISSUE THREAD

**Issue by saganshul** [felicity-buzz/Felicity-buzz2k15#2]
Use the scroll magic library(http://scrollmagic.io/)

**Comment by darkcoderrises** [comment]
karna kya chahta hai bhai mere
aur karwana bhi

**Comment by saganshul** [comment]
See the animation on the page I am planning to have animation like that.

**Comment by Motwani** [comment]
Bhai kisko kya assign kiya hai?

Assign some task to me. I will try to do it this week.

**Comment by saganshul** [comment]
Select one work of your choice.

**Comment by saganshul** [comment]
You can watch my work at anshulsinghal.me/buzz-demo/

**Comment by saganshul** [comment]
Task completed.
Can be found at felicity.iiit.ac.in/buzz or anshulsinghal.me/buzzdemo
Please give your suggestions so that we can improve it.
