### ISSUE TITLE
deciding content for gordain knot event.

### ISSUE THREAD

**Issue by abhishekgarg16** [felicity-buzz/Felicity-buzz2k15#6]
Guys, i am planning to work on the backend part of gordian knot event. for that i need to know the details of the event and what all needs to be implemented.
Write in comments what all needs to be done.

**Comment by saganshul** [comment]
priority order - 
1) levels
2) constraints for submission
3) Use the authentication app for guardian knot
4) Leaderboard

**Comment by abhishekgarg16** [comment]
should its format be like a question followed by four choices?

**Comment by saganshul** [comment]
Consult this with coordinators of guardian knot ( satyam pandey).
Kitna mujhe pta hai Dono tarah ke ho sakte hai input field type bhi aur multiple tye bhi

**Comment by saganshul** [comment]
i am now continuing on  abhishek work
