### ISSUE TITLE
gordian knot models.

### ISSUE THREAD

**Issue by varunnaganathan** [felicity-buzz/Felicity-buzz2k15#9]
guys in the gordian knot models ,the answer field is set to CharField..shouldnt it be an integerfield??I think all gordian knot answers are always integers?

**Comment by saganshul** [comment]
Yaa, I we can either make it char or integer. Because If we take it as char then string matching or if we use Integer field then equalizing.

**Comment by saganshul** [comment]
if all answers will be in Integer then we should use interger. Okay! I will correct it today!
